resources:
  - route_guide_client_streaming.yaml
  - ingress.yaml
patches:
- path: deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: route-guide-client-streaming-deployment
