resources:
  - route_guide_bidirectional_streaming.yaml
  - ingress.yaml
patches:
- path: deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: route-guide-bidirectional-streaming-deployment
