[package]
org = "ballerina"
name = "grpc_tests"
version = "1.3.1"

[[platform.java11.dependency]]
path = "../native/build/libs/grpc-native-1.3.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/grpc-test-utils-1.3.1-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ballerina-cli-2201.2.0-20220607-123700-52fedf4d.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-3.20.1.jar"

[[platform.java11.dependency]]
path = "./lib/proto-google-common-protos-1.17.0.jar"

[[platform.java11.dependency]]
path = "./lib/formatter-core-2201.2.0-20220607-123700-52fedf4d.jar"
