---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: route-guide-unary
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/grpc-backend: "true"
spec:
  rules:
  - host: bal.perf.test
    http:
      paths:
      - path: "/"
        backend:
          service:
            name: route-guide-unary
            port:
              number: 9090
