resources:
  - ballerina_adservice.yaml
  - ingress.yaml
patches:
- path: deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: ballerina-adservice-deployment
